# Generated by Django 3.2.18 on 2023-03-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230322_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hocluc',
            fields=[
                ('masv', models.OneToOneField(db_column='MaSV', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.sinhvien')),
                ('sotinchi', models.IntegerField(blank=True, db_column='SoTinChi', null=True)),
                ('thangdiem10', models.FloatField(blank=True, db_column='ThangDiem10', null=True)),
                ('thangdiem4', models.FloatField(blank=True, db_column='ThangDiem4', null=True)),
                ('diemchu', models.CharField(blank=True, db_column='DiemChu', max_length=255, null=True)),
                ('xeploai', models.CharField(blank=True, db_column='XepLoai', max_length=255, null=True)),
            ],
            options={
                'db_table': 'HocLuc',
                'managed': False,
            },
        ),
    ]
