# Generated by Django 3.2.18 on 2023-04-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_authgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
    ]
